name: Collect Stock Data

on:
  schedule:
    - cron: "0 23 * * 1-5" # Roda às 23h nos dias úteis
    - cron: "0 4 * * 1-5" # Roda às 4h nos dias úteis
  workflow_dispatch: # Permite execução manual

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yfinance
          pip install -r requirements.txt

      - name: Run collector
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/collect_history.py
